packaging_format = 2

id = "hugo"
name = "Hugo"
description.en = "Static Site Generator"
description.fr = "Générateur de blog statique"

version = "0.146.7~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://gohugo.io"
admindoc = "https://gohugo.io/documentation"
code = "https://github.com/gohugoio/hugo"

[integration]
yunohost = ">= 12.0.14"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hugo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.site_name]
    ask.en = "Choose a directory name for your site (used for `hugo new site name` command)"
    ask.fr = "Choisissez le nom de répertoire pour votre site (utilisé dans la commande `hugo new site nom`)"
    type = "string"
    default = "site"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/gohugoio/hugo/releases/download/v0.146.7/hugo_extended_0.146.7_linux-amd64.tar.gz"
    amd64.sha256 = "d910f6a17c467f74eb77da46cd7357c7c48612a517eb513beb35d9f1172e6a91"
    arm64.url = "https://github.com/gohugoio/hugo/releases/download/v0.146.7/hugo_extended_0.146.7_linux-arm64.tar.gz"
    arm64.sha256 = "7144c637db0d9ef95e8290302fce328c05d7376eed1236aabc3f4431014a5fff"
    armhf.url = "https://github.com/gohugoio/hugo/releases/download/v0.146.7/hugo_0.146.7_linux-arm.tar.gz"
    armhf.sha256 = "057291ee187b0da7a620fddf32447bb8a6c0f3c01fed5e2f1973ebb28863ca0a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.arm64 = ".*arm64.tar.gz"
    autoupdate.asset.armhf = ".*arm.tar.gz"

    [resources.system_user]
    allow_ssh = true
    allow_sftp = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    
